import { localDay, practiceStreak, heatData, heatmapMarkup, trendMarkup } from './progress.mjs';

const historyEscape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const historyNumber = value => Number(value || 0).toLocaleString('tr-TR',{maximumFractionDigits:1});
const historyClock = seconds => `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
export function historyView(data, modes, sessions, shortcuts, days, layoutId, modeFilter = 'ALL') {
  const layout=data.keyboards[layoutId], layoutSessions=sessions.filter(s=>s.keyboardLayout===layoutId);
  const filtered=layoutSessions.filter(s=>modeFilter === 'ALL' || s.exerciseType===modeFilter);
  const comparable=filtered.filter(s=>!['EXPLORE','FIND','LETTERS','SHORTCUTS'].includes(s.exerciseType));
  const streak=practiceStreak(days), stats=heatData(sessions,layoutId);
  const average=key=>comparable.length?comparable.reduce((sum,s)=>sum+s[key],0)/comparable.length:0;
  const availableModes=Object.entries(modes).filter(([id])=>id !== 'SHORTCUTS');
  const calendar=Array.from({length:14},(_,index)=>{
    const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-13+index);
    const day=localDay(date), practiced=days.includes(day);
    return `<span class="practice-day ${practiced?'was-practiced':''}" title="${date.toLocaleDateString('tr-TR')}: ${practiced?'çalışma yapıldı':'çalışma kaydı yok'}"><small>${date.toLocaleDateString('tr-TR',{weekday:'short'})}</small><strong>${date.getDate()}</strong><span class="sr-only">${practiced?'Çalışma yapıldı':'Çalışma kaydı yok'}</span></span>`;
  }).join('');
  const weak=Object.entries(stats).filter(([key,s])=>s.errors && !['fazladan',' '].includes(key)).sort((a,b)=>b[1].errors/b[1].attempts-a[1].errors/a[1].attempts || b[1].errors-a[1].errors).slice(0,5);
  const first=comparable[0],last=comparable.at(-1), ownShortcuts=shortcuts.filter(s=>s.keyboardLayout===layoutId);
  return `<div class="eyebrow">KÜÇÜK ÇALIŞMALAR, KALICI ALIŞKANLIKLAR</div><h1>Gelişimim</h1><p class="guide-intro">Doğruluğunu, ritmini ve çalışma alışkanlığını takip et.</p>
  <section class="panel"><div class="section-head"><h2>Çalışma serin</h2><span class="badge">${streak.today?'Bugünün çalışması tamam':'Bugün kısa bir çalışma yapabilirsin'}</span></div><div class="metrics metric-three"><div class="metric"><strong id="streak-current">${streak.current}</strong><span>günlük seri</span></div><div class="metric"><strong>${streak.best}</strong><span>en uzun kayıtlı seri</span></div><div class="metric"><strong>${streak.totalDays}</strong><span>kayıtlı çalışma günü</span></div></div><div class="practice-calendar">${calendar}</div><p class="muted">Son 14 gün · Aynı gün yapılan çalışmalar bir gün sayılır. Seri, bu tarayıcıdaki kayıtlı günlerden hesaplanır; bugün henüz çalışmadıysan dünkü seri korunur.</p></section>
  <section class="panel"><div class="form-grid"><label class="field">İncelenen klavye<select id="history-layout">${Object.entries(data.keyboards).map(([id,item])=>`<option value="${id}" ${id===layoutId?'selected':''}>${item.name}</option>`).join('')}</select></label><label class="field">Grafik ve sonuç filtresi<select id="history-mode"><option value="ALL">Tüm çalışmalar</option>${availableModes.map(([id,item])=>`<option value="${id}" ${id===modeFilter?'selected':''}>${item[0]}</option>`).join('')}</select></label></div><p class="muted" style="margin-top:12px">Q ve F sonuçları ayrı değerlendirilir. Farklı çalışma türlerini karşılaştırmak için filtreyi kullan.</p></section>
  <section class="panel"><div class="section-head"><h2>Zayıf tuş ısı haritası</h2><span class="badge">${layout.name}</span></div><p class="muted">Bu klavyenin kayıtlı ${layoutSessions.length} yazma çalışması · Renk, yanlış vuruş / toplam vuruş oranıdır. Az örnekle yapılan ölçümler değişebilir.</p>${heatmapMarkup(layout,stats)}<div class="heat-legend"><span class="heat-none">Veri yok</span><span class="heat-good">%0</span><span class="heat-mild">%1–9</span><span class="heat-warm">%10–24</span><span class="heat-hot">%25 ve üzeri</span></div><p id="heat-detail" class="guide-message" role="status">Bir tuşa dokunarak vuruş ve hata sayılarını görebilirsin.</p>${weak.length?`<p class="weak-summary">Öncelik verebileceğin tuşlar: ${weak.map(([key,s])=>`${historyEscape(key.toLocaleUpperCase('tr-TR'))} (${s.errors}/${s.attempts}${s.attempts<5?', az örnek':''})`).join(' · ')}</p>`:'<p class="weak-summary">Henüz hata kaydı yok. Birkaç çalışma yaptıkça harita oluşacak.</p>'}<div class="actions"><button data-mode="WEAK" data-training-layout="${layoutId}">${layout.name} ile zayıf tuşları çalış</button></div></section>
  <section class="panel"><h2>Hız ve doğruluk yolculuğun</h2>${comparable.length?`<div class="metrics metric-three"><div class="metric"><strong>${comparable.length}</strong><span>grafikteki çalışma</span></div><div class="metric"><strong>${historyNumber(average('realWordsPerMinute'))}</strong><span>ortalama doğru kelime / dk</span></div><div class="metric"><strong>%${historyNumber(average('accuracy'))}</strong><span>ortalama ilk vuruş doğruluğu</span></div></div>`:''}<div class="trend-grid"><div><h3>Doğru kelime / dakika</h3>${trendMarkup(comparable,'realWordsPerMinute','Doğru kelime / dakika','kelime/dk')}</div><div><h3>İlk vuruş doğruluğu (%)</h3>${trendMarkup(comparable,'accuracy','İlk vuruş doğruluğu','%')}</div></div>${last?`<p class="muted">İlk kayıtlı çalışmaya göre ${historyNumber(last.realWordsPerMinute-first.realWordsPerMinute)} kelime/dk ve ${historyNumber(last.accuracy-first.accuracy)} yüzde puan değişim. Harf keşfi ve kısayol çalışmaları hız grafiğine katılmaz.</p>`:'<p class="muted">Bir kelime veya metin çalışmasını tamamladığında grafik oluşacak.</p>'}</section>
  <section class="panel table-wrap"><h2>Yazma sonuçları</h2>${filtered.length?`<table><caption class="muted">Filtrede ${filtered.length} çalışma · Toplamda son ${data.config.historyLimit} yazma sonucu saklanır.</caption><thead><tr><th>Tarih</th><th>Çalışma</th><th>Kelime/dk</th><th>Doğruluk</th><th>Süre</th></tr></thead><tbody>${[...filtered].reverse().map(s=>`<tr><td>${new Date(s.startedAt).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'})}</td><td>${historyEscape(modes[s.exerciseType]?.[0] || s.exerciseType)}${s.turkishSet?`<small class="set-caption">${historyEscape(data['turkish-sets'][s.turkishSet]?.name || s.turkishSet)}</small>`:''}</td><td>${['EXPLORE','FIND','LETTERS'].includes(s.exerciseType)?'—':historyNumber(s.realWordsPerMinute)}</td><td>%${historyNumber(s.accuracy)}</td><td>${historyClock(s.durationSeconds)}</td></tr>`).join('')}</tbody></table>`:'<p class="chart-empty">Bu filtrede henüz sonuç yok. İlk kısa çalışmanı tamamlayabilirsin.</p>'}</section>
  <section class="panel"><h2>Kısayol sonuçları</h2>${ownShortcuts.length?`<div class="table-wrap"><table><caption class="muted">Son ${ownShortcuts.length} kısayol çalışması · Ayrı değerlendirilir.</caption><thead><tr><th>Tarih</th><th>Tamamlanan</th><th>Doğru deneme</th><th>Süre</th></tr></thead><tbody>${[...ownShortcuts].reverse().map(s=>`<tr><td>${new Date(s.startedAt).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'})}</td><td>${s.completed} / 10</td><td>%${Math.round(s.correct/s.attempts*100)}</td><td>${historyClock(s.durationSeconds)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="chart-empty">Kısayol atölyesini tamamladığında sonuçların burada görünecek.</p>'}<button data-mode="SHORTCUTS">Kısayolları çalış</button></section>
  <div class="actions"><button id="export-history">Geçmişi JSON olarak indir</button><button data-nav="home">Çalışmalara dön</button></div><div class="tip">Sonuçlar bu cihazın bu tarayıcısında saklanır. Tarayıcı verilerini temizlemek geçmişini ve çalışma serini siler. Çalışma günleri, son 20 sonuçtan ayrı tutulur (en fazla 366 gün).</div>`;
}
